export const newsData = [
 {
  "id": 0,
  "day": "0",
  "ticker": "TURT",
  "headline": "Push to EV bill has been rejected",
  "description": "The push to EV has been rejected by senators in the government, this comes as a shock to the original stance of the government. EV companies are facing the heat with many of them relying on subsidaries.",
  "source": "Primetime news",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 1,
  "day": "0",
  "ticker": "TURT",
  "headline": "CEO confirms EV subsidies not needed",
  "description": "CEO confirms subsidies are not required to hit the market for the company. Ensures this will not affect the company over the long term. ",
  "source": "CEO press conference",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 2,
  "day": "0",
  "ticker": "TURT",
  "headline": "EV stocks crumble",
  "description": "EV stocks from various car companies are seen tumbling with the bill being rejected. Companies are facing hard time trying to convince customers about their alternative plans.",
  "source": "Stock market",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 3,
  "day": "0",
  "ticker": "TURT",
  "headline": "Record sales by car manufacturer",
  "description": "Car manufacturer reported record sales of their cars. Analyst advises caution advised as this is a smaller number compared to other larger car manufacturers.",
  "source": "Primetime news",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 4,
  "day": "1",
  "ticker": "TURT",
  "headline": "CEO sells stocks to pay his tax.",
  "description": "CEO continues to vent his frustration for being overly taxed. Confirms he will not sell anymore as he's cleared all the taxes. Plans to move his company away to a different location. ",
  "source": "Primetime news",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 5,
  "day": "7",
  "ticker": "TURT",
  "headline": "Car recall over defect",
  "description": "Over 500k cars have been recalled as a manufacturing defect has been identified. ",
  "source": "Reputed blog",
  "credibility": "4",
  "analyst_opinion": "Reputed analyst claims this isn't a big deal as the camera fault is easily fixed. ",
  "": ""
 },
 {
  "id": 6,
  "day": "12",
  "ticker": "TURT",
  "headline": "Nickel found for battery!",
  "description": "A landmark deal to boost battery production and help overcome the supply shortage that has ravaged the market for months now. Nickel helps make the batteries that EVs run on.",
  "source": "News article",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 7,
  "day": "19",
  "ticker": "TURT",
  "headline": "Where is the promised car?",
  "description": "Friend rants about how he hasn't received a date for the car he had placed an order for. News articles also talk about a possible production delay (2nd delay) ",
  "source": "News and social media",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 8,
  "day": "26",
  "ticker": "TURT",
  "headline": "CEO talks about supple chain woes",
  "description": "CEO spoke about delay in production of the new cars. Confirms factories are running below capacity, but records show that the company's revenue is still growing.",
  "source": "CEO interview",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 9,
  "day": "46",
  "ticker": "TURT",
  "headline": "Favorite celebrity buys a car",
  "description": "A famous celebrity shows off his new car on Twitter, claims it's the best car in the world and everyone should get one as soon as possible.",
  "source": "Social media",
  "credibility": "1",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 10,
  "day": "66",
  "ticker": "TURT",
  "headline": "New factories setup",
  "description": "Factories are being setup in multiple countries to boost production. CEO calls it the beginning of good time for production.",
  "source": "CEO interview",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 11,
  "day": "75",
  "ticker": "TURT",
  "headline": "Export boost reported",
  "description": "Production numbers in the rise as cars from a country flood the country confirns a reputed source. CEO claims this will be touted as the next production hub.",
  "source": "News article",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 12,
  "day": "88",
  "ticker": "TURT",
  "headline": "Advice from a friend",
  "description": "A friend claims he knows a person who works in Tesla very well, says the stock is going to tank soon and advises you to sell.",
  "source": "Friend advice",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 13,
  "day": "96",
  "ticker": "TURT",
  "headline": "No stopping the surge",
  "description": "News report claim the stocks are surging and will continue to do so for the next couple of months. All factories are working to their maximum capacity with new ones coming up soon.",
  "source": "News article",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 14,
  "day": "99",
  "ticker": "TURT",
  "headline": "Production factory issues?",
  "description": "One of the biggest factories are reporting unexpected civic unrest in the country, forcing factories to be closed for an undetermined time.",
  "source": "News article",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 15,
  "day": "119",
  "ticker": "TURT",
  "headline": "Company racing past production goals",
  "description": "The company continues to race past production goals, with it's working factories. There is an uptick with car sales and delivery. ",
  "source": "News article",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 16,
  "day": "129",
  "ticker": "TURT",
  "headline": "CEO's social media rant",
  "description": "The CEO goes on a social media rant claiming that he's being targetted by governments. Says the main reason for the company suffering is the absence of ease in governance.",
  "source": "Social media",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 17,
  "day": "139",
  "ticker": "TURT",
  "headline": "Troubling times ahead?",
  "description": "Industries across the world slows down as a global material looms, several factors such as economy, health and governanace. ",
  "source": "News ",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 18,
  "day": "160",
  "ticker": "TURT",
  "headline": "Hiring freeze",
  "description": "Several companies are freezing hiring as companies believe the market is heading towards a recession.",
  "source": "News",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 19,
  "day": "175",
  "ticker": "TURT",
  "headline": "CEO plans on acquisitions",
  "description": "CEO hints on possible acquisitions on social media.",
  "source": "Social media",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 20,
  "day": "187",
  "ticker": "TURT",
  "headline": "Notification from a friend",
  "description": "A friend claims he got a job at the company. Would this mean the hiring is back to normal?",
  "source": "Friend advice",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 21,
  "day": "194",
  "ticker": "TURT",
  "headline": "Deliveries stalled once again",
  "description": "Car deliveries have been stalled once again due to labour shortages",
  "source": "News article",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 22,
  "day": "0",
  "ticker": "Croc",
  "headline": "Crocodile almost loses its throne ",
  "description": "Crocodile first took over from Bunny as the world's most valuable tech company in 2015, and there has been years of toing and froing between the two as each has raced to out-innovate the other and be the most valuable company on Wall Street. However, Crocodile is investing more heavily in saving the world they have pledge to have a fully cabon neutral supply chain by 2030",
  "source": "Prime news",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 23,
  "day": "0",
  "ticker": "Croc",
  "headline": "President Biden's rigth to repair order ",
  "description": "Biden signed a sweeping executive order (EO) directing a multitude of federal agencies to promote additional competition in the U.S. economy. One such directive encourages the Federal Trade Commission (FTC) to enact additional regulations that prohibit manufacturer policies barring the repair of equipment and devices by individuals and independent repair shops.",
  "source": "News ",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 24,
  "day": "0",
  "ticker": "Croc",
  "headline": "Crocodile ups the ante",
  "description": "Crocodile wins last minute reprieve from App Store changes while 'Fortnite' appeal play out. The lowe court did not find that Crocodile violated any antitrust laws.",
  "source": "Reuters",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 25,
  "day": "0",
  "ticker": "Croc",
  "headline": "Jerry Gomez Leaves Crocodile",
  "description": "With top executives leaving the most traditional Silicon Valley business, Crocodile is suffering another lost as Gomez, its VP Marcom Intergration, who is departing from the company after a liitlw more then two years in this role. ",
  "source": "9To5Mac",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 26,
  "day": "1",
  "ticker": "Croc",
  "headline": "The first member if the $3tn Club ",
  "description": "Crocodile became the first US company to be valued at over $3tn on as the tech company continued its phenomenal share price growth, tripling in value in under four years.",
  "source": "The Guardian ",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 27,
  "day": "13",
  "ticker": "Croc",
  "headline": "What We should all be buying? ",
  "description": "Crocodile is the best think to by no mattre what! Think abou it is the only Tech company that everyone goes crazy about everytime they are releasing a new product.",
  "source": "twitter ",
  "credibility": "1",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 28,
  "day": "18",
  "ticker": "Croc",
  "headline": "Crocodile vs Netherland ",
  "description": "Crocodile is no stranger to antitrust cases. Which mean that it refers to the regulation of th cinceentration of economic power, particulary in regarding to monopolies. According to history thy are strarting to become faiirly familiar wiith lossing them as well, most resently in Netherlands, allowing Dutch datiing apps to offer non-Crocodile payment optioins. ",
  "source": "News ",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 29,
  "day": "28",
  "ticker": "Croc",
  "headline": "Crocodile Sweet Quarter ",
  "description": "Crocodile has a double edge in China which makes up one-fifth of its sales. US sanctions helped Crocodile gain market share in China because they blocked Chincese competitors form getting key componetws and softwate for phones. ",
  "source": "snapchat ",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 30,
  "day": "34",
  "ticker": "Croc",
  "headline": "Regulators close in on App Store",
  "description": "the competition bill regulators and politicians ramp up thir scrutint of the growiing industry. In addtiion the senate  is hoping that the the Open App Markets Act will target the commission. This bill was passes despite Crocodile's urge for it to be dismissed given how much revenue it'll wipe away. ",
  "source": "twitter ",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 31,
  "day": "41",
  "ticker": "Croc",
  "headline": "Crocodile and Crypto?",
  "description": "the news crypto feature, alloews user to for the tap to pay, which creates a contackless payment systeem and after Covid that\u2019s all we want. It is important to also note that crypto enthusiasts want Web3 to take control away from Big Tech.",
  "source": "News ",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 32,
  "day": "48",
  "ticker": "Croc",
  "headline": "People want Jose to get Cooked ",
  "description": "Crocodile CEO faces a shareholder revolt over his massive pay package. Her resives $99m pay abd bonuses package. This means that the massive jump of 14.8m he got in 2020. this indicates that severeal sharehoolder are making themselves heard across the tech industry. ",
  "source": "News ",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 33,
  "day": "67",
  "ticker": "Croc",
  "headline": "Crocodile releases some sparkly new stuff",
  "description": "THE SHOCK MOVED DOWN. 1.17% this could be because there is  pressure on big tech stocks atm as Russia destabizes global markets. Thanks for nothing Russia ",
  "source": "Magazine",
  "credibility": "1",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 34,
  "day": "71",
  "ticker": "Croc",
  "headline": "Foxconn bites into Crocodile\u2019s production targets",
  "description": "China's new covid suge force tech giants to shut down their local operations. The Bank of America analysts are cautions about \"prolongued supply impact\". However it has not cut any current quarter estimates, though investors were less forgiving and sent the stock down 2.66% to its lowest price. ",
  "source": "News ",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 35,
  "day": "80",
  "ticker": "Croc",
  "headline": "Crocodile Shares the Fruit basket",
  "description": "New product coming out as Crocodile hints at a UK Crocodile Card on the way with its latest credut rating tech purchase. It is imporatnt to note that Credit Kudos helps lenders make better informed decisions by tracking banking data. ",
  "source": "news ",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 36,
  "day": "85",
  "ticker": "Croc",
  "headline": "Crocodile refines its protfolio ",
  "description": "WE ARENT TO KEEN ON THE CROC-PHONE SE ANYMORE. Which is probably why Crocodile is cutting its CROC-PHONE SE outout by 20% in the next quarter as the model receiives weaker-than expected demans in China. Also Electronics demand is taking a hit in the face of the Ukraine war.",
  "source": "YouTube",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 37,
  "day": "96",
  "ticker": "Croc",
  "headline": "Is Crocodile losing its Crunch?",
  "description": "the CFO, has just stated that the supply constraints are waiting to bite into its balance sheet. Since there are several challenges ahead, with inflation. Covid in China means production shut downs, and supply constraints are here tp stay- all which could hurt sales by as much as  $8bn. ",
  "source": "news ",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 38,
  "day": "110",
  "ticker": "Croc",
  "headline": "The Faang gang is down ",
  "description": "Crocodile has lost its title as world's most valuable company. Even, with a down of over 20% Crocodile is still the most valuable company in the USA. Many people are wondering what this could really mean for the market in the long run? ",
  "source": "News ",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 39,
  "day": "132",
  "ticker": "Croc",
  "headline": "Time to Edit ",
  "description": "Its about time that Crocodile gives a edit feature that includes on undo send as well as mark as unread. Even with all of this releases, the stock remained flat, which worries people since its down 20% compare to this time last year. ",
  "source": "twitter ",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 40,
  "day": "135",
  "ticker": "Croc",
  "headline": "what is going on with the market right now?",
  "description": "Crocodile keep going down should we start to get worry or should Sell! Everything. Crocodile needs to start to let its invester know why sell are also down. No Way that they are still struggling form COVID!",
  "source": "YouTube",
  "credibility": "1",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 41,
  "day": "149",
  "ticker": "Croc",
  "headline": "Think have turn to the better!",
  "description": "it is about time that the stock for Crocodile has started to go up. Many people belive that Crocodile is turning around and making a come back form how it was it has been. I would jugest everyone too BUY!",
  "source": "twitter ",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 42,
  "day": "171",
  "ticker": "Croc",
  "headline": "Crocodile and cars",
  "description": "since 2000, Crocodile has filed for and publiish a total of 248 automobiile related patents. It is important to noter that this inclues: self-driving technology, riding comfort, seat, suspeensions, navigariooin, battery management, vehicle-to-everything coonnectivity for car to car communication.",
  "source": "news ",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 43,
  "day": "0",
  "ticker": "GIRA",
  "headline": "Giraffe third quarter results",
  "description": "Coconut's and Yam's advertising revenues have increased significantly from last year. However, Yam's advertising revenue was less than its expected goal. Coconut Cloud's revenue was also less than its expected goal.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 44,
  "day": "0",
  "ticker": "GIRA",
  "headline": "Notification from a friend",
  "description": "Your friend advises you to invest in Giraffe, claiming that it is one of the safest bets in the market.",
  "source": "Friend",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 45,
  "day": "3",
  "ticker": "GIRA",
  "headline": "Several states file complaints against Giraffe",
  "description": "Several states have filed complaints against Giraffe, accusing Giraffe of abusing its monopoly power",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 46,
  "day": "3",
  "ticker": "GIRA",
  "headline": "Bobby Smith invests in over 5000 shares of Giraffe",
  "description": "Popular celebrity Bobby Smith invested in over 5000 shares of Giraffe",
  "source": "News",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 47,
  "day": "6",
  "ticker": "GIRA",
  "headline": "Coconut spends over $500 million on cybersecurity",
  "description": "Coconut's latest purchase of $500 million is for improving the cybersecurity of its Cloud",
  "source": "News",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 48,
  "day": "15",
  "ticker": "GIRA",
  "headline": "Coconut reveals its first public blockchain project",
  "description": "Coconut joins the other social media platforms in moving towards crypto. Coconut revealed its first public blockchain project, as well as its blockchain team.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 49,
  "day": "15",
  "ticker": "GIRA",
  "headline": "A post on social media",
  "description": "Ex-Coconut CEO Mary Johnson posted on social media, stating that they started investing in crypto",
  "source": "Social media",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 50,
  "day": "15",
  "ticker": "GIRA",
  "headline": "Ex-Coconut CEO Mary Johnson gets involved with the company's first public blockchain project",
  "description": "Mary Johnson, Coconut's previous CEO, has joined the blockchain project as a strategic advisor",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 51,
  "day": "21",
  "ticker": "GIRA",
  "headline": "Giraffe's self driving car, Almond, fights against competition",
  "description": "Almond filed a lawsuit against the DMV, trying to hide its self-driving accidents from the public eye. Almond refuses to share its safety protocols, arguing that it would be a disavantage in the competitive market.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 52,
  "day": "21",
  "ticker": "GIRA",
  "headline": "A post on social media",
  "description": "A user posted on social media, claiming that self-driving cars are the future.",
  "source": "Social media",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 53,
  "day": "21",
  "ticker": "GIRA",
  "headline": "A post on social media",
  "description": "A user posted on social media, claiming that Almond's testers are required to sign nondisclosure agreements. The user also claims that self-driving cars are not reliable, and that there are more self-driving accidents than companies reveal.",
  "source": "Social media",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 54,
  "day": "21",
  "ticker": "GIRA",
  "headline": "Giraffe announces a stock split",
  "description": "Giraffe announces a stock split, increasing the availability of its shares",
  "source": "News",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 55,
  "day": "21",
  "ticker": "GIRA",
  "headline": "A notification from a friend",
  "description": "Your friend advises you to invest in Giraffe because of the stock split",
  "source": "Friend",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 56,
  "day": "21",
  "ticker": "GIRA",
  "headline": "A notification from a friend",
  "description": "Your friend advises you to invest in Giraffe before the stock split",
  "source": "Friend",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 57,
  "day": "42",
  "ticker": "GIRA",
  "headline": "Coconut purchases cybersecurity company Acorn",
  "description": "Coconut spent 5 billion dollars on cybersecurity company Acorn. Acorn is one of Giraffe's biggest acquisitions ever.",
  "source": "News",
  "credibility": "5",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 58,
  "day": "57",
  "ticker": "GIRA",
  "headline": "Almond is ready to hit the road",
  "description": "After years of development and testing, Almond is ready to hit the road. ",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 59,
  "day": "72",
  "ticker": "GIRA",
  "headline": "Giraffe's stock plummets",
  "description": "Giraffe's stock prices are plummeting.",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 60,
  "day": "72",
  "ticker": "GIRA",
  "headline": "A post on social media",
  "description": "The CEO of Giraffe posts on social media, claiming that the stock's under performance is not their fault. Ad spending had to be decreased because of another war in another country.",
  "source": "Interview",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 61,
  "day": "81",
  "ticker": "GIRA",
  "headline": "Coconut reveals its new products",
  "description": "Coconut is working on releasing the Mango Watch, the Mango 9 smartphone, and the Mango Pro earbuds.",
  "source": "News",
  "credibility": "",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 62,
  "day": "111",
  "ticker": "GIRA",
  "headline": "Giraffe's stocks are going to split soon",
  "description": "Giraffe's stocks are going to split soon. Investors will receive additional shares per share they own.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 63,
  "day": "114",
  "ticker": "GIRA",
  "headline": "Giraffe reduces hiring",
  "description": "Giraffe is reducing hiring due to inflation and war",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 64,
  "day": "117",
  "ticker": "GIRA",
  "headline": "A notification from a friend",
  "description": "A friend who works at Google expresses their fears of lay-offs",
  "source": "Friend",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 65,
  "day": "0",
  "ticker": "BUNY",
  "headline": "Bunny stock prices approach all-time high",
  "description": "Bunny's stock prices are quickly approaching the all-time high stock price that it recently achieved",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 66,
  "day": "0",
  "ticker": "BUNY",
  "headline": "Antitrust officials target Bunny",
  "description": "Antitrust officials are investigating Bunny's acquisition of Carrot, a speech-to-text software.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 67,
  "day": "0",
  "ticker": "BUNY",
  "headline": "A post on social media",
  "description": "A user posts on social media, claiming that Bunny's true all-time high is soon to come",
  "source": "Social media",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 68,
  "day": "9",
  "ticker": "BUNY",
  "headline": "Bunny is developing its in-house chip",
  "description": "Bunny recently hired one of the top semiconductor engineers to help develop its in-house Arm-based chip.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 69,
  "day": "12",
  "ticker": "BUNY",
  "headline": "Bunny and Alpaca strike Lettuce deal",
  "description": "Bunny and Alpaca strike a deal, agreeing to integrate the Lettuce video conferencing software in Alpaca's products",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 70,
  "day": "18",
  "ticker": "BUNY",
  "headline": "Bunny sales top $50 billion",
  "description": "Bunny's sales topped $50 billion for the first time. However, the revenue for Bunny's cloud computing service, Potato, has been overestimated the last few quarters.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 71,
  "day": "21",
  "ticker": "BUNY",
  "headline": "A notification from a friend",
  "description": "Your friend advises you to invest in Bunny because it is a strong stock and is likely to soar again",
  "source": "Friend",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 72,
  "day": "27",
  "ticker": "BUNY",
  "headline": "Bunny considers acquiring cybersecurity firm Acorn",
  "description": "Bunny is considering acquiring cybersecurity firm Acorn which has a market value of $4 billion.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 73,
  "day": "39",
  "ticker": "BUNY",
  "headline": "Bunny completes its $15 billion acquisition of Carrot",
  "description": "Bunny has completed its $15 billion acquisition of Carrot, a speech-to-text software",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 74,
  "day": "48",
  "ticker": "BUNY",
  "headline": "Bunny faces antitrust complaints",
  "description": "Bunny is facing antitrust complaints about Potato, its cloud computing service",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 75,
  "day": "48",
  "ticker": "BUNY",
  "headline": "A post on social media",
  "description": "A user posts on social media, claiming that Bunny abuses its power, undermines fair competition, and limits consumer choice in the cloud computing market",
  "source": "Social media",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 76,
  "day": "72",
  "ticker": "BUNY",
  "headline": "Bunny shares surge as much as 8%",
  "description": "Bunny shares surged as much as 8% in Wednesday's extending trading",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 77,
  "day": "90",
  "ticker": "BUNY",
  "headline": "A notification from a friend",
  "description": "A friend claims that Microsoft can continue thriving despite the recession",
  "source": "Friend",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 78,
  "day": "93",
  "ticker": "BUNY",
  "headline": "Bunny intends to increase wages for current employees",
  "description": "Bunny intends to increase wages for current employees despite the reduction in hiring",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 79,
  "day": "93",
  "ticker": "BUNY",
  "headline": "A post on social media",
  "description": "A user posts on social media, claiming that Bunny is one of the most resilient and undervalued stocks.",
  "source": "Social media",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 80,
  "day": "96",
  "ticker": "BUNY",
  "headline": "Bunny reduces estimates",
  "description": "Bunny reduced its revenue estimates by about $1 billion.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 81,
  "day": "96",
  "ticker": "BUNY",
  "headline": "Bunny faces the effects of inflation",
  "description": "Bunny gets half of its revenue from outside the country, so inflation has negatively affected the company.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 82,
  "day": "102",
  "ticker": "BUNY",
  "headline": "Bunny has lost 30% YTD",
  "description": "Bunny has lost 30% YTD. Can Bunny recover from the losses?",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 83,
  "day": "105",
  "ticker": "BUNY",
  "headline": "A post on social media",
  "description": "A user posts on social media, claiming that the bear market is an advantage for long-term investors. They also claimed that Bunny has continuously rewarded long-term shareholders.",
  "source": "Social media",
  "credibility": "2",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 84,
  "day": "114",
  "ticker": "BUNY",
  "headline": "Bunny targeted by antitrust officials once again",
  "description": "One of Bunny's recent acquistions is being investigated by antitrust officials. Antitrust officials want to find out whether this acquisition will undermine competition.",
  "source": "News",
  "credibility": "4",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 85,
  "day": "117",
  "ticker": "BUNY",
  "headline": "Bunny cuts some jobs",
  "description": "Bunny cuts some jobs, claiming that the layoff is not related to the recession",
  "source": "News",
  "credibility": "3",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 86,
  "day": "0",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Studies show that overconfident investors trade more than rational investors and that doing so lowers their expected utilities. Greater overconfidence leads to greater trading and to lower expected utility.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 87,
  "day": "7",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Your best bet to overcome the pitfalls of overconfidence is to slow down your thinking and simply become aware of it, and question whether you\u2019re maybe being overly optimistic. Don\u2019t act in haste.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 88,
  "day": "14",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Be confident, yet intellectually humble. Consider the possibility that you could be wrong. Listen to evidence that could possible change your mind. Be ruthless with your investment thesis. Be open-minded.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 89,
  "day": "21",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Consider the consequences of being wrong. Your job should be first and foremost not to lose money. Put your ego aside and keep that in mind.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 90,
  "day": "28",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Don\u2019t view each problem in isolation. The single best advice we have in framing is broad framing. See the decision as a member of a class of decisions that you\u2019ll probably have to take.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 91,
  "day": "35",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Don\u2019t underplay regret. Regret is probably the greatest enemy of good decision making in personal finance. So if you are an asset manager or financial adviser, assess how prone clients are to it. The more potential for regret, the more likely they are to churn their account, sell at the wrong time, and buy when prices are high. High-net-worth individuals are especially risk averse, so try to gauge just how risk averse. Clients who have regrets will often fire their advisers.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 92,
  "day": "42",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Seek out good advice. Part of getting a wide-ranging perspective is to cultivate curiosity and to seek out guidance. An ideal adviser is a person who likes you and doesn\u2019t care about your feelings.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 93,
  "day": "49",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Probably the most compelling evidence is that most investors, especially active investors, both professional and amateur, tend to have a very hard time beating market indices consistently, as demonstrated in the latest\u00a0Morningstar Active-Passive Barometer.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 94,
  "day": "56",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "How can you tackle overconfidence bias? You could look back at your trading records and ask yourself questions such as \u201cwhy did I buy or sell that stock?\u201d and try to give an objective answer. If you can spot behavioural patterns in your trading activity, it\u2019s easier to correct these mistakes.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 95,
  "day": "63",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "I have seen overconfidence in action many times over my practice. To counteract this behavior in my clients, I often recommend they establish a \u201cmad money\u201d account. This involves taking a small portion of one\u2019s wealth for \u201coverconfident\u201d trading activities while leaving the remainder of their wealth to be managed in a disciplined way. This approach scratches the itch that many investors have to trade their account, while at the same time keeping the majority of the money intelligently managed.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 96,
  "day": "70",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Effective investing doesn\u2019t come naturally to most of us. Even when we know the fundamentals, we tend to make snap decisions and irrational--sometimes destructive--mistakes, based on what \u201cfeels\u201d right. The gamification built into platforms like Robinhood\u2014free stock for signing up, frequently updating and colourful screens based on performance, even digital confetti upon completion of a successful transaction\u2014may at times, just worsen these tendencies.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 97,
  "day": "77",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "In a study we conducted on a nationally representative sample of the U.S population, we found evidence that although most Americans are overconfident (67 per cent of the sample), people currently in Generation Z are significantly more overconfident\u2014even more than millennials and Gen Xers. We also know that Robinhood\u2019s average user is 31 years old, and half of them are first-time investors. This premise of innate investing knowledge, combined with a platform that rewards hasty decisions with immediate gratification and self-flattery, makes for a breeding ground of biased decisions.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 98,
  "day": "84",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "For instance, compared with people with low bias, people who showed high levels of overconfidence were twice as likely to be struggling with their financial lives: having the lowest savings, the highest debt, and the worst credit scores.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 99,
  "day": "91",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "If you\u2019re overconfident, you might overestimate your knowledge and abilities, which in turn can lead you to overestimate expected returns and underestimate investment risks. Overconfidence can also result in excessive trading. One phenomenon investors often fall prey to is the so-called Hot Hand Fallacy where they assume that a winning streak will continue, whether it is a top-performing fund manager, a stock that has soared, or their own investment choices.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 100,
  "day": "98",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "Reviewing your trading records can be a good exercise to reduce overconfidence bias. While conducting your review, it\u2019s important to remain objective. Ask yourself questions such as \u201cwhy did I buy that security?\u201d or \u201cwhy did I sell?\u201d. If you can identify behavioral patterns in your trading activity, it\u2019s easier to correct for mistakes.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 101,
  "day": "105",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "While it is very possible to outperform indices and people do all the time, it is not probable--and that is the point. Most investors, both professional and amateur, tend to have a very hard time beating market indices consistently.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
 {
  "id": 102,
  "day": "112",
  "ticker": "Advisor",
  "headline": "Advisor",
  "description": "In recent years, investors have begun to realise that trading frequently hurts, higher fees and commissions hurt, and overconfidence hurts.",
  "source": "Advisor",
  "credibility": "0",
  "analyst_opinion": "-",
  "": ""
 },
]